# Generated by Django 4.0.5 on 2022-06-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='db',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('end_year', models.CharField(max_length=10)),
                ('intensity', models.IntegerField()),
                ('sector', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=1000)),
                ('insight', models.CharField(max_length=1000)),
                ('url', models.CharField(max_length=10000)),
                ('region', models.CharField(max_length=100)),
                ('start_year', models.CharField(max_length=10)),
                ('impact', models.CharField(max_length=100)),
                ('added', models.CharField(max_length=1000)),
                ('published', models.CharField(max_length=1000)),
                ('country', models.CharField(max_length=1000)),
                ('relevance', models.IntegerField()),
                ('pestle', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('likelihood', models.IntegerField()),
            ],
        ),
    ]
