# Generated by Django 4.0.5 on 2022-06-21 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db',
            old_name='likelihood',
            new_name='hood',
        ),
    ]
