# Generated by Django 4.0.5 on 2022-06-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_rename_likelihood_db_hood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db',
            name='end_year',
            field=models.IntegerField(),
        ),
    ]
