# Generated by Django 4.0.5 on 2022-06-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0003_alter_db_end_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db',
            name='end_year',
            field=models.CharField(max_length=10),
        ),
    ]
